import { IconType } from "react-icons";
import {
  SiReact,
  SiNextdotjs,
  SiTypescript,
  SiTailwindcss,
  SiPrisma,
  SiPostgresql,
  SiFramer,
  SiNodedotjs,
  SiDocker,
  SiOpenzeppelin,
  SiShadcnui,
  SiChakraui,
  SiVuedotjs,
  SiChartdotjs,
} from "react-icons/si";

export const TECH_ICONS: Record<string, IconType> = {
  react: SiReact,
  nextjs: SiNextdotjs,
  typescript: SiTypescript,
  tailwind: SiTailwindcss,
  prisma: SiPrisma,
  postgres: SiPostgresql,
  framer: SiFramer,
  nodejs: SiNodedotjs,
  postgresql: SiPostgresql,
  docker: SiDocker,
  zustand: SiOpenzeppelin,
  shadcn: SiShadcnui,
  chakraui: SiChakraui,
  vue: SiVuedotjs,
  chartdotjs: SiChartdotjs,
};
